# Generated by Django 2.1.3 on 2019-03-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shelf', '0002_auto_20190318_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='no_of_copy',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
