# Generated by Django 2.1.3 on 2019-03-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shelf', '0005_auto_20190401_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, help_text='2018-12-02', null=True, verbose_name='died'),
        ),
    ]
