# Generated by Django 2.1.3 on 2019-03-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shelf', '0006_auto_20190401_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(help_text='surname only', max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(help_text='middle name inclusive', max_length=100),
        ),
    ]
